### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by takaaki-k** [takaaki-k/protospace-38906#1]
https://protospace-38906.onrender.com

**Comment by shodai-ito** [comment]
@takaaki-k さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`プロトタイプ詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること**
プロトタイプのタイトルが正しく表示さされていないため、修正をお願いします。
<img width="755" alt="スクリーンショット 2023-05-03 15 35 45" src="https://user-images.githubusercontent.com/62537107/235847442-90c9af59-7fe4-46ab-83b8-9fed59043100.png">

### **`コメント機能`**
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のコメントが投稿できてしまうため、修正をお願いします。
<img width="1088" alt="スクリーンショット 2023-05-03 15 35 52" src="https://user-images.githubusercontent.com/62537107/235847499-ad1d8898-cf3b-4039-9e58-d98ba046eddf.png">

### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
トップページのプロトタイプ投稿者名をクリックすると、プロトタイプ詳細ページに遷移してしまいます。
ユーザー詳細ページに遷移するよう実装お願いします。
<img width="560" alt="スクリーンショット 2023-05-03 15 35 30" src="https://user-images.githubusercontent.com/62537107/235847680-8cb50d9e-562a-4422-8b7d-69809240dd6a.png">

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザー名の一部が正しく表示されておりません。
正しいユーザー名が表示されるよう修正をお願いします。
<img width="641" alt="スクリーンショット 2023-05-03 15 36 16" src="https://user-images.githubusercontent.com/62537107/235847789-c0aa2517-3b91-497e-884a-8bdfc6a32141.png">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takaaki-k** [comment]
ご確認ありがとうございます。
修正して再度依頼させていただきました。

**Comment by shodai-ito** [comment]
@takaaki-k さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by takaaki-k** [comment]
> @takaaki-k さん、ご提出ありがとうございます‼︎ 正常に動作することが確認できました！　LGTMです✨　 おめでとうございます🎉
> 
> 次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^） 別途、最終課題の案内をチャンネルに送らせて頂きます。 今しばらくお待ちください。

**Comment by takaaki-k** [comment]
@shodai-ito さんご確認ありがとうございました。
